name: Bug Report
description: File a bug report.
title: "[Bug]: [short_description]"
labels: ["bug", "help wanted"]
assignees: ["JasperKimmel"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: markdown
    attributes:
      value: "## BUG details"
  - type: input
    id: short_description
    attributes:
      label: Short description of the bug
      description: A short description of your bug, like an emails subject.
      placeholder: ex. Error 10007 when changing feedback settings.
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce the issue
      description: Tell us how to reproduce the behavior.
      placeholder: |
        1. Go to 'Settings'
        2. Enable/Disable 'Audio Feedback'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: I would expect the app to save the feedback settings withouth any error.
    validations:
      required: false     
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: app-version
    attributes:
      label: APP Version
      description: What version of our software are you running?
      options:
        - 1.0.0
      default: 0
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Mobile platform
      description: On which mobile platform is our app running?
      options:
        - Apple iPhone (iOS)
        - Apple Watch (WatchOS)
      multiple: false
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
